name: obwi-with-ollama
services:
    open-webui:
        ports:
            - 3034:8080
        volumes:
            - ./ollama:/root/.ollama
            - ./open-webui:/app/backend/data
        container_name: open-webui
        restart: always
        image: ghcr.io/open-webui/open-webui:ollama
volumes:
    ollama:
        external: true
        name: ollama
    open-webui:
        external: true
        name: open-webui
